FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# RestaurantStock

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

[
{
"Name":"Soup of the Day (Check Specials Board)",
"Description":"",
"Price":"€5.95",
"Image":"",

},{
"Name":"Bruschetta",
"Description":"(Contains G, N, MK, E) Topped with Buffalo Mozzarella, Sun-Dried Tomato & Basil Pesto",
"Price":"€6.95",
"Image":"",

},{
"Name":"Chicken Wings",
"Description":"(Contains MK, CY) Hot ‘n’ Spicy wings, celery spear, blue cheese & garlic dip",
"Price":"€8.95 ",
"Image":"",

},{
"Name":"Baby Ribs",
"Description":"(Contains MK, S, SP) Slow cooked pork ribs glazed with BBQ sauce and served with chargrilled corn on the cob",
"Price":"€9.95",
"Image":"",

},{
"Name":"Feta Cheese Salad",
"Description":"(Contains MK, N) Dressed leaves, Cherry tomatoes, Beetroot & Walnuts topped with Feta Cheese",
"Price":"€6.95",
"Image":"",

},{
"Name":"Prawn Pil Pil",
"Description":"(Contains MK, G, C) Sauté Dublin bay prawns in a hot chilli & garlic oil, sourdough bread",
"Price":"€12.95",
"Image":"",
""
},{
"Name":"Black Pudding Salad",
"Description":"(Contains G, E) Tom’s finest black pudding tossed on the pan with bacon, sauté potato & topped with poached egg, tossed leaves & balsamic glaze",
"Price":"€8.95",
"Image":"",

},{
"Name":"Nachos",
"Description":"(Contains G, MK) Chilli beef nachos, tortilla chips, sour cream & salsa OR Veggies with mix courgette, peppers & onion in a tomato sauce with melting cheese",
"Price":"€8.95",
"Image":"",

},{
"Name":"Fish Cakes",
"Description":"(Contains G, MK, C, E, SS, N) Fresh cod, salmon & crab meat in a sesame crumb, chilli, coriander & lime mayonnaise, Rocket & pesto dressing",
"Price":"€8.95",
"Image":"",

},{
"Name":"Stocky's Sharing Plate",
"Description":"(Contains G, MK, CY, E, S) Chicken Wings (Your Way), Crispy Potato Skins, Chilli Beef Nachos & Smoked Applewood Wheel

Wings – Choose from Hot ‘n’ Spicy, Sticky Honey Glaze or BBQ Sauc",
"Price":"€17.95",
"Image":"",

},{
"Name":"Herb-roasted Beef Tenderloin",
"Description":"with Bordelaise sauce served with herb roasted new potatoes and a ragout of summer squash",
"Price":"€17.95",
"Image":"",

},{
"Name":"Chicken Cordon Bleu",
"Description":"with tasso ham and fontina cheese served with a potato gratin and mustard cream sauce",
"Price":"",
"Image":"",

},{
"Name":"Veal Parmesan",
"Description":"with fettucine and marinara sauce",
"Price":"",
"Image":"",

},{
"Name":"Kansas City BBQ glazed Meatloaf",
"Description":" with twice-baked potatoes and ratatouille",
"Price":"",
"Image":"",

},{
"Name":"Pork Tenderloin",
"Description":"stuffed with red pepper, spinach and goat cheese served with sweet potatoes and braised red cabbage",
"Price":"",
"Image":"",

},{
"Name":"Coq au Vin a la Bourguignonne",
"Description":"Sauteed Chicken in a red wine sauce with bacon, mushrooms, pearl onions served with roasted garlic potato puree",
"Price":"",
"Image":"",

},{
"Name":"Herb-basted Chicken Breast with Chasseur sauce",
"Description":"served with glazed potatoes and a vegetable ragout",
"Price":"",
"Image":"",

},{
"Name":"Curried Chicken",
"Description":"with sauteed onions and diced tomatoes served with coconut rice",
"Price":"",
"Image":"",

},{
"Name":"Pan-seared Sea Scallops and Shrimp",
"Description":"served with creamed corn and fresh tomatoes",
"Price":"",
"Image":"",

},{
"Name":"Honey, soy-glazed Salmon Filet",
"Description":" with creamed leeks and mushrooms",
"Price":"",
"Image":"",

},{
"Name":"Red Snapper Filet",
"Description":"basted with herbs and a lemon cream sauce served with roasted potatoes and a summer squash gratin",
"Price":"",
"Image":"",

},{
"Name":"Pad Thai with Chicken and Shrimp",
"Description":"
Pad Thai with Chicken and Shrimp -- served with egg rolls and sweet red pepper dipping sauce",
"Price":"",
"Image":""
},{
"Name":"Crawfish Etouffee",
"Description":"with fragrant basmati rice",
"Price":"",
"Image":""
},{
"Name":"Spinach Vegetable Lasagna",
"Description":"with marinara sauce and classic caesar salad",
"Price":"",
"Image":""
},{
"Name":"Pad Thai with Chicken and Shrimp",
"Description":"
Pad Thai with Chicken and Shrimp -- served with egg rolls and sweet red pepper dipping sauce",
"Price":"",
"Image":""
},{
"Name":"Chocolate Fudge Cake",
"Description":"With Belgian chocolate sauce, real dairy ice cream, salted caramel crunch pearls and chocolate fudge pieces",
"Price":"",
"Image":""
},{
"Name":"Cherry Pie",
"Description":"Dark sweet cherry pie, dusted with demerara sugar, served hot with your choice of real dairy ice cream, custard or fluffy cream",
"Price":"",
"Image":""
},{
"Name":"Caramel Biscuit Cheesecake",
"Description":"Baked New York style cheesecake with a buttery biscuit base, served with toffee fudge sauce, chocolate fudge pieces and fluffy cream",
"Price":"",
"Image":""
},{
"Name":"Lemon Meringue Pie",
"Description":"With raspberries in sauce, real dairy ice cream and a white chocolate and raspberry shard",
"Price":"",
"Image":""
},{
"Name":"Coconut and Black Cherry Rice Pudding",
"Description":"Slowly cooked in coconut milk, served with raspberries in sauce",
"Price":"",
"Image":""
},{
"Name":"Treacle Sponge",
"Description":"A fluffy sponge with lots of sticky treacle, and your choice of real dairy ice cream, custard or fluffy cream",
"Price":"",
"Image":""
},{
"Name":"Belgian Chocolate Brownie",
"Description":"The perfect brownie, with a raspberry & white chocolate shard and real dairy ice cream",
"Price":"",
"Image":""
}
  
];


### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }